// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tp02SisWeb2.Data;

namespace Tp02SisWeb2.Migrations
{
    [DbContext(typeof(PortoContext))]
    [Migration("20200928220210_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tp02SisWeb2.Models.BL", b =>
                {
                    b.Property<int>("IdBl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Consigner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Navio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Num")
                        .HasColumnType("int");

                    b.HasKey("IdBl");

                    b.ToTable("BLs");
                });

            modelBuilder.Entity("Tp02SisWeb2.Models.Container", b =>
                {
                    b.Property<int>("IdContainer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BLIdBl")
                        .HasColumnType("int");

                    b.Property<int>("IdBl")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numContainer")
                        .HasColumnType("int");

                    b.Property<string>("tamanho")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdContainer");

                    b.HasIndex("BLIdBl");

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("Tp02SisWeb2.Models.Container", b =>
                {
                    b.HasOne("Tp02SisWeb2.Models.BL", "BL")
                        .WithMany("containers")
                        .HasForeignKey("BLIdBl");
                });
#pragma warning restore 612, 618
        }
    }
}
